FROM jenkins/jenkins:lts

USER root

# Instalar Node.js 20 LTS
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm@latest

# Instalar Docker CLI (para sonar-scanner via Docker)
RUN apt-get update && apt-get install -y docker.io

USER jenkins
